import random

print("Welcome to Mad Libs!!")
print("Welcome!!")
print("Choose a story template:")
print("1 - Hospital")
print("2 - Camping")
print("3 - Fantasy Letter")

template = input("Enter 1, 2 or 3: ")

if template == "1":
    print("Type number:")
    number = input()
    print("Type measure of time:")
    time = input()
    print("Type mode of transportation:")
    transport = input()
    print("Type adjective:")
    adjective1 = input()
    print("Type another adjective:")
    adjective2 = input()
    print("Type noun:")
    noun1 = input()
    print("Type color:")
    color = input()
    print("Type part of the body:")
    body_part1 = input()
    print("Type verb:")
    verb1 = input()
    print("Type another number:")
    number2 = input()
    print("Type another noun:")
    noun2 = input()
    print("Type another noun:")
    noun3 = input()
    print("Type another part of the body:")
    body_part2 = input()
    print("Type another verb:")
    verb2 = input()
    print("Type another noun:")
    noun4 = input()
    print("Type one more adjective:")
    adjective3 = input()
    print("Type silly word:")
    silly_word = input()
    print("Type final noun:")
    noun5 = input()

    print("\nHere's your story:\n")
    print("It was about", number, time, "ago when I arrived at the hospital in a", transport + ".")
    print("The hospital is a/an", adjective1, "place, there are a lot of", adjective2, noun1, "here.")
    print("There are nurses here who have", color, body_part1 + ".")
    print("If someone wants to come into my room I told them that they have to", verb1, "first.")
    print("I’ve decorated my room with", number2, noun2 + ".")
    print("Today I talked to a doctor and they were wearing a", noun3, "on their", body_part2 + ".")
    print("I heard that all doctors", verb2, noun4, "every day for breakfast.")
    print("The most", adjective3, "thing about being in the hospital is the", silly_word, noun5 + "!")

elif template == "2":
    print("Type a person’s name:")
    name = input()
    print("Type a noun:")
    noun1 = input()
    print("Type an adjective (feeling):")
    adjective1 = input()
    print("Type a verb:")
    verb1 = input()
    print("Type another adjective (feeling):")
    adjective2 = input()
    print("Type an animal:")
    animal1 = input()
    print("Type another verb:")
    verb2 = input()
    print("Type a color:")
    color = input()
    print("Type a verb ending in 'ing':")
    verb_ing = input()
    print("Type an adverb ending in 'ly':")
    adverb = input()
    print("Type a number:")
    number = input()
    print("Type a measure of time:")
    time = input()
    print("Type another color:")
    color2 = input()
    print("Type another animal:")
    animal2 = input()
    print("Type another number:")
    number2 = input()
    print("Type a silly word:")
    silly_word = input()
    print("Type another noun:")
    noun2 = input()

    print("\nHere's your story:\n")
    print("This weekend I am going camping with", name + ".")
    print("I packed my lantern, sleeping bag, and", noun1 + ".")
    print("I am so", adjective1, "to", verb1, "in a tent.")
    print("I am", adjective2, "we might see a(n)", animal1 + ", I hear they’re kind of dangerous.")
    print("While we’re camping, we are going to hike, fish, and", verb2 + ".")
    print("I have heard that the", color, "lake is great for", verb_ing + ".")
    print("Then we will", adverb, "hike through the forest for", number, time + ".")
    print("If I see a", color2, animal2, "while hiking, I am going to bring it home as a pet!")
    print("At night we will tell", number2, silly_word, "stories and roast", noun2, "around the campfire!!")

elif template == "3":
    print("Type a person’s name:")
    name = input()
    print("Type an adjective:")
    adjective1 = input()
    print("Type a color:")
    color = input()
    print("Type an animal:")
    animal = input()
    print("Type a place:")
    place = input()
    print("Type another adjective:")
    adjective2 = input()
    print("Type magical creature (plural):")
    creature1 = input()
    print("Type another adjective:")
    adjective3 = input()
    print("Type another magical creature (plural):")
    creature2 = input()
    print("Type a room in a house:")
    room = input()
    print("Type a noun:")
    noun1 = input()
    print("Type another noun:")
    noun2 = input()
    print("Type plural noun:")
    plural_noun1 = input()
    print("Type another adjective:")
    adjective4 = input()
    print("Type plural noun:")
    plural_noun2 = input()
    print("Type number:")
    number = input()
    print("Type measure of time:")
    time = input()
    print("Type verb ending in 'ing':")
    verb_ing = input()
    print("Type another adjective:")
    adjective5 = input()
    print("Type another noun:")
    noun3 = input()

    print("\nHere's your story:\n")
    print("Dear", name + ",")
    print("I am writing to you from a", adjective1, "castle in an enchanted forest.")
    print("I found myself here one day after going for a ride on a", color, animal, "in", place + ".")
    print("There are", adjective2, creature1, "and", adjective3, creature2, "here!")
    print("In the", room, "there is a pool full of", noun1 + ".")
    print("I fall asleep each night on a", noun2, "of", plural_noun1, "and dream of", adjective4, plural_noun2 + ".")
    print("It feels as though I have lived here for", number, time + ".")
    print("I hope one day you can visit, although the only way to get here now is", verb_ing, "on a", adjective5, noun3 + "!!")

else:
    print("Invalid choice.")
